# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editAdminDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_editAdminDialog(object):
    def setupUi(self, editAdminDialog, mainPage, admin):
        self.editAdminDialog = editAdminDialog
        self.editAdminDialog.setObjectName("editAdminDialog")
        self.editAdminDialog.setEnabled(True)
        self.editAdminDialog.resize(485, 430)
        self.editAdminDialog.setModal(True)
        self.mainPage = mainPage
        self.newAdminBtns = QtWidgets.QDialogButtonBox(editAdminDialog)
        self.newAdminBtns.setEnabled(True)
        self.newAdminBtns.setGeometry(QtCore.QRect(230, 380, 221, 41))
        self.newAdminBtns.setOrientation(QtCore.Qt.Horizontal)
        self.newAdminBtns.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.newAdminBtns.setObjectName("newAdminBtns")
        self.usernameFld = QtWidgets.QLineEdit(editAdminDialog)
        self.usernameFld.setGeometry(QtCore.QRect(30, 50, 421, 31))
        self.usernameFld.setObjectName("usernameFld")
        self.UsernameLbl = QtWidgets.QLabel(editAdminDialog)
        self.UsernameLbl.setGeometry(QtCore.QRect(30, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UsernameLbl.setFont(font)
        self.UsernameLbl.setObjectName("UsernameLbl")
        self.passwordFld = QtWidgets.QLineEdit(editAdminDialog)
        self.passwordFld.setGeometry(QtCore.QRect(30, 120, 421, 31))
        self.passwordFld.setObjectName("passwordFld")
        self.passwordLbl = QtWidgets.QLabel(editAdminDialog)
        self.passwordLbl.setGeometry(QtCore.QRect(30, 90, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLbl.setFont(font)
        self.passwordLbl.setObjectName("passwordLbl")
        self.firstNameLbl = QtWidgets.QLabel(editAdminDialog)
        self.firstNameLbl.setGeometry(QtCore.QRect(30, 160, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.firstNameLbl.setFont(font)
        self.firstNameLbl.setObjectName("firstNameLbl")
        self.firstNameFld = QtWidgets.QLineEdit(editAdminDialog)
        self.firstNameFld.setGeometry(QtCore.QRect(30, 190, 421, 31))
        self.firstNameFld.setObjectName("firstNameFld")
        self.middleNameLbl = QtWidgets.QLabel(editAdminDialog)
        self.middleNameLbl.setGeometry(QtCore.QRect(30, 230, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.middleNameLbl.setFont(font)
        self.middleNameLbl.setObjectName("middleNameLbl")
        self.middleNameFld = QtWidgets.QLineEdit(editAdminDialog)
        self.middleNameFld.setGeometry(QtCore.QRect(30, 260, 421, 31))
        self.middleNameFld.setObjectName("middleNameFld")
        self.middleNameFld.setPlaceholderText("(Optional)")
        self.lastNameLbl = QtWidgets.QLabel(editAdminDialog)
        self.lastNameLbl.setGeometry(QtCore.QRect(30, 300, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastNameLbl.setFont(font)
        self.lastNameLbl.setObjectName("lastNameLbl")
        self.lastNameFld = QtWidgets.QLineEdit(editAdminDialog)
        self.lastNameFld.setGeometry(QtCore.QRect(30, 330, 421, 31))
        self.lastNameFld.setObjectName("lastNameFld")
        self.admin = admin
        self.usernameFld.setText(self.admin.username)
        self.passwordFld.setText(self.admin.password)
        self.firstNameFld.setText(self.admin.fName)
        self.middleNameFld.setText(self.admin.mName)
        self.lastNameFld.setText(self.admin.lName)
        self.label = QtWidgets.QLabel(editAdminDialog)
        self.label.setGeometry(QtCore.QRect(190, 80, 121, 21))
        self.label.setStyleSheet("color: #a94442;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(editAdminDialog)
        self.label_2.setGeometry(QtCore.QRect(190, 150, 121, 21))
        self.label_2.setStyleSheet("color: #a94442;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(editAdminDialog)
        self.label_3.setGeometry(QtCore.QRect(190, 220, 121, 21))
        self.label_3.setStyleSheet("color: #a94442;")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(editAdminDialog)
        self.label_4.setGeometry(QtCore.QRect(190, 360, 121, 21))
        self.label_4.setStyleSheet("color: #a94442;")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(editAdminDialog)
        self.newAdminBtns.accepted.connect(self.okButton)
        self.newAdminBtns.rejected.connect(editAdminDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(editAdminDialog)

    def retranslateUi(self, editAdminDialog):
        _translate = QtCore.QCoreApplication.translate
        editAdminDialog.setWindowTitle(_translate("editAdminDialog", "Dialog"))
        self.UsernameLbl.setText(_translate("editAdminDialog", "Username:"))
        self.passwordLbl.setText(_translate("editAdminDialog", "Password:"))
        self.firstNameLbl.setText(_translate("editAdminDialog", "First Name:"))
        self.middleNameLbl.setText(_translate("editAdminDialog", "Middle Name:"))
        self.lastNameLbl.setText(_translate("editAdminDialog", "Last Name:"))

    def okButton(self):
        username = self.usernameFld.text()
        password = self.passwordFld.text()
        fName = self.firstNameFld.text()
        mName = self.middleNameFld.text()
        lName = self.lastNameFld.text()
        count = 0
        # sb = self.buttonBox.standardButton(button)
        # if self.newAdminBtns.:


        
        if username == "":
            print("EMPTY FIELDS")
            # #FF0000
            self.label.setText("Please fill out this field.")
        else:
            self.label.setText("")
            mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_sars"
            )
            mycursor = mydb.cursor()
            query = "SELECT * FROM admin WHERE '" + username + "' LIKE username"
            mycursor.execute(query)
            result = mycursor.fetchone()

            if result is None:
                count += 1
            else:
                self.label.setText("Username already taken")

        if password == "":
            self.label_2.setText("Please fill out this field.")
        else:
            self.label_2.setText("")
            count += 1

        if fName == "":
            self.label_3.setText("Please fill out this field.")
        else:
            self.label_3.setText("")
            count += 1

        if lName == "":
            self.label_4.setText("Please fill out this field.")
        else:
            self.label_4.setText("")
            count += 1

        if count == 4:
            mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_sars"
            )
            mycursor = mydb.cursor()
            query = f"UPDATE admin SET username = '{username}', password = '{password}', firstname = '{fName}', middlename = '{mName}', lastname = '{lName}' WHERE admin_id LIKE {self.admin.userId}"
            mycursor.execute(query)
            mydb.commit()
            print("Aba ayos ah")
            self.mainPage.loadAdminTable()
            self.editAdminDialog.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editAdminDialog = QtWidgets.QDialog()
    ui = Ui_editAdminDialog()
    ui.setupUi(editAdminDialog)
    editAdminDialog.show()
    sys.exit(app.exec_())
